### ISSUE TITLE
seems fail with chinese utf8 

### ISSUE THREAD

**Issue by jinleileiking** [airbnb/superset#2473]
when use sql lab:

if a table contains Chinese utf8 character:

it fails:

```
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb7 in position 1: invalid start byte
```

**Comment by jinleileiking** [comment]
```
| user  | CREATE TABLE `user` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `openid` varchar(256) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '微信openid',
  `mobile` bigint(20) NOT NULL DEFAULT '0' COMMENT '手机号',
  `password` varchar(256) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '密码',
  `avatar_link` varchar(512) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '用户头像',
  `nickname` varchar(32) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '用户昵称',
  `ip` varchar(32) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '用户ip',
  `gender` tinyint(4) NOT NULL DEFAULT '0' COMMENT '性别0未填写1男2女',
  `rc_token` varchar(512) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '融云的token',
  `room_thumbnail_link` varchar(512) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '房间缩略图',
  `room_name` varchar(32) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '房间名',
  `create_time` int(11) NOT NULL DEFAULT '0' COMMENT '创建用户时间',
  `update_time` int(11) NOT NULL DEFAULT '0' COMMENT '更新用户信息时间',
  `status` tinyint(4) NOT NULL DEFAULT '0' COMMENT '用户状态0注册成功1未注册成功',
  `session_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '' COMMENT '手机注册用户的sessionId',
  PRIMARY KEY (`id`),
  KEY `user_mobile_index` (`mobile`)
) ENGINE=InnoDB AUTO_INCREMENT=212 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci |
```

**Comment by jinleileiking** [comment]
```
mysql> select * from user limit 1\G
*************************** 1. row ***************************
                 id: 1
             openid: oUffWw4max8mP-FM2gLsDId3yBos
             mobile: 0
           password:
        avatar_link: http://wx.qlogo.cn/mmopen/Q3auHgzwzM6G8U77Zg3z97CF4DgVVzAA4BxgEESPPiauKG6DIBuRlRMic2EBjFddvk6FVV9kiczdVBjCfWdTibaVmjvhwibboMDk8LPxsv3Z2MIs/0
           nickname: 青梅煮马
                 ip: 114.255.44.139
             gender: 1
room_thumbnail_link:
          room_name: 嗯
        create_time: 0
        update_time: 0
             status: 0
         session_id:
```
